name: Python Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: make install

    - name: Run the Flask application
      run: |
        nohup make run &
        sleep 5
      # 使用 nohup 和 & 将 Flask 应用程序放入后台运行，并使用 sleep 5 秒确保服务器启动

    - name: Check if server is running
      run: |
        curl -f http://localhost:3000 || exit 1
      # 使用 curl 检查服务器是否在运行，如果未运行则失败

    - name: Shutdown Flask application
      run: |
        pkill -f "python app.py" || true
      # 关闭 Flask 应用程序
